//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateRP6Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateRP6Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;RP6RobotBaseLib.h&gt;
        ///#include &lt;someCommonLib.h&gt;
        ///#include &quot;base.h&quot;
        ///
        ///int main(void)
        ///{
        ///	setup();
        ///	someCommonFunction();
        ///	while(true) 
        ///	{
        ///		loop();
        ///	}
        ///	return 0;
        ///}
        ///
        ///void setup(void)
        ///{
        ///	powerON();
        ///}
        ///
        ///void loop(void)
        ///{
        ///
        ///}.
        /// </summary>
        internal static string base_c {
            get {
                return ResourceManager.GetString("base_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifndef base_HEADER
        ///#define base_HEADER
        ///void setup(void);
        ///void loop(void);
        ///#endif.
        /// </summary>
        internal static string base_h {
            get {
                return ResourceManager.GetString("base_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comma:= ,
        ///empty:=
        ///space:= $(empty) $(empty)
        ///
        ///mkfile_path := $(subst  $(space),$(empty),$(abspath $(lastword $(MAKEFILE_LIST))))
        ///project_name := $(notdir $(patsubst %/,%,$(dir $(mkfile_path))))
        ///
        ///TARGET = $(project_name)
        ///
        ///COMMON_DIR=../common
        ///RP6_LIB_PATH=$(AVR32_HOME)/RobotLoader/RP6Lib
        ///RP6_LIB_PATH_OTHERS=$(COMMON_DIR) $(RP6_LIB_PATH) $(RP6_LIB_PATH)/RP6control $(RP6_LIB_PATH)/RP6common $(RP6_LIB_PATH)/RP6base $(RP6_LIB_PATH)/RP6control_M256_WIFI
        ///
        ///SRC_COMMON=$(wildcard $(COMMON_DIR)/*.c) $(wild [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string base_makefile {
            get {
                return ResourceManager.GetString("base_makefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///IF not DEFINED AVR32_HOME GOTO :NOTINSTALLED
        ///
        ///SET PATH=%AVR32_HOME%\bin;%PATH%
        ///SET LANG=C
        ///SET mypath=%~dp0
        ///SET robotloader_cmd_exe=&quot;%AVR32_HOME%\RobotLoader\robotloader_cmd.exe&quot;
        ///SET robotloader_path=&quot;%AVR32_HOME%\RobotLoader\&quot;
        ///SET project_path=%mypath:~0,-1%\
        ///
        ///cd /D &quot;%project_path%&quot;
        ///
        ///for /f &quot;delims=\&quot; %%a in (&quot;%project_path%&quot;) do SET project_name=%%~nxa
        ///SET hexfile=&quot;%project_path%%project_name%.hex&quot;
        ///
        ///echo ------------------- clean -------------------
        ///make clean
        ///
        ///echo ---------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BUILDUPLOAD_bat {
            get {
                return ResourceManager.GetString("BUILDUPLOAD_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int someCommonFunction()
        ///{
        ///	return 1;
        ///}.
        /// </summary>
        internal static string common_someCommonLib_c {
            get {
                return ResourceManager.GetString("common_someCommonLib_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifndef someCommonLib_HEADER
        ///#define someCommonLib_HEADER
        ///int someCommonFunction();
        ///#endif.
        /// </summary>
        internal static string common_someCommonLib_h {
            get {
                return ResourceManager.GetString("common_someCommonLib_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;RP6ControlLib.h&gt;
        ///#include &lt;someCommonLib.h&gt;
        ///#include &quot;control.h&quot;
        ///
        ///int main(void)
        ///{
        ///	setup();
        ///	someCommonFunction();
        ///	while(true) 
        ///	{
        ///		loop();
        ///	}
        ///	return 0;
        ///}
        ///
        ///void setup(void)
        ///{
        ///	initRP6Control();
        ///}
        ///
        ///void loop(void)
        ///{
        ///
        ///}.
        /// </summary>
        internal static string control_c {
            get {
                return ResourceManager.GetString("control_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifndef control_HEADER
        ///#define control_HEADER
        ///void setup(void);
        ///void loop(void);
        ///#endif.
        /// </summary>
        internal static string control_h {
            get {
                return ResourceManager.GetString("control_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comma:= ,
        ///empty:=
        ///space:= $(empty) $(empty)
        ///
        ///mkfile_path := $(subst  $(space),$(empty),$(abspath $(lastword $(MAKEFILE_LIST))))
        ///project_name := $(notdir $(patsubst %/,%,$(dir $(mkfile_path))))
        ///
        ///TARGET = $(project_name)
        ///
        ///COMMON_DIR=../common
        ///RP6_LIB_PATH=$(AVR32_HOME)/RobotLoader/RP6Lib
        ///RP6_LIB_PATH_OTHERS=$(COMMON_DIR) $(RP6_LIB_PATH) $(RP6_LIB_PATH)/RP6control $(RP6_LIB_PATH)/RP6common $(RP6_LIB_PATH)/RP6base $(RP6_LIB_PATH)/RP6control_M256_WIFI
        ///
        ///SRC_COMMON=$(wildcard $(COMMON_DIR)/*.c) $(wild [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string control_makefile {
            get {
                return ResourceManager.GetString("control_makefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 2013
        ///VisualStudioVersion = 12.0.31101.0
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}&quot;) = &quot;PROJECTNAME&quot;, &quot;PROJECTNAME.vcxproj&quot;, &quot;{37A42495-D54F-4BA1-9C69-788A3AFFD401}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		BASE - COMPILE AND UPLOAD|Win32 = BASE - COMPILE AND UPLOAD|Win32
        ///		CONTROL - COMPILE AND UPLOAD|Win32 = CONTROL - COMPILE AND UPLOAD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PROJECTNAME_sln {
            get {
                return ResourceManager.GetString("PROJECTNAME_sln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project DefaultTargets=&quot;Build&quot; ToolsVersion=&quot;12.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup Label=&quot;ProjectConfigurations&quot;&gt;
        ///    &lt;ProjectConfiguration Include=&quot;BASE - COMPILE AND UPLOAD|Win32&quot;&gt;
        ///      &lt;Configuration&gt;BASE - COMPILE AND UPLOAD&lt;/Configuration&gt;
        ///      &lt;Platform&gt;Win32&lt;/Platform&gt;
        ///    &lt;/ProjectConfiguration&gt;
        ///    &lt;ProjectConfiguration Include=&quot;CONTROL - COMPILE AND UPLOAD|Win32&quot;&gt;
        ///      &lt;Configuration&gt;CONTROL - COMPILE AND  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PROJECTNAME_vcxproj {
            get {
                return ResourceManager.GetString("PROJECTNAME_vcxproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup&gt;
        ///    &lt;Filter Include=&quot;util&quot;&gt;
        ///      &lt;UniqueIdentifier&gt;{76f63abe-dacf-423a-85f6-56b679a2a892}&lt;/UniqueIdentifier&gt;
        ///    &lt;/Filter&gt;
        ///    &lt;Filter Include=&quot;source&quot;&gt;
        ///      &lt;UniqueIdentifier&gt;{fca16c96-6b2d-4420-8213-b4384f5c0954}&lt;/UniqueIdentifier&gt;
        ///    &lt;/Filter&gt;
        ///    &lt;Filter Include=&quot;source\base&quot;&gt;
        ///      &lt;UniqueIdentifier&gt;{e2622d19-c9a2-4303-b9db-dd5f9b6091d4}&lt;/UniqueIdent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PROJECTNAME_vcxproj_filters {
            get {
                return ResourceManager.GetString("PROJECTNAME_vcxproj_filters", resourceCulture);
            }
        }
    }
}
